In [46]:
import pandas as pd

csv = pd.read_csv('201904 sales reciepts.csv')
df = pd.DataFrame(csv)

df = df[df['product_id'].between(1, 21)]
quantity_sum_by_product_id = df.groupby('product_id')['quantity'].sum()

quantity_sum_by_product_id_sorted = quantity_sum_by_product_id.sort_values(ascending=False)

print(quantity_sum_by_product_id_sorted)

product_id
8     95
1     70
6     70
9     67
20    65
2     65
17    57
13    55
11    54
3     53
16    52
7     51
5     50
21    50
10    48
14    48
15    48
4     47
12    45
18    42
19    36
Name: quantity, dtype: int64

In [47]:
filtered_df = df[df['product_id'].isin([6, 1, 8])]
final_out = filtered_df.groupby(['transaction_date', 'product_id'])['quantity'].sum()
final_out=final_out.reset_index().rename(columns={'quantity': 'quantity'})
final_out
# final_out.to_csv('Top3TeaCoffee.csv')

   transaction_date  product_id  quantity
0        2019-04-07           1         1
1        2019-04-07           6         2
2        2019-04-07           8         1
3        2019-04-08           1        11
4        2019-04-08           6         5
..              ...         ...       ...
57       2019-04-26           6         1
58       2019-04-26           8         1
59       2019-04-27           1         1
60       2019-04-27           6         2
61       2019-04-27           8         2

[62 rows x 3 columns]

In [48]:


date_range = pd.date_range(start='2019-04-01', end='2019-04-30', freq='D')  
product_ids = [1, 6, 8]
all_combinations = pd.DataFrame([(date, product_id) for date in date_range for product_id in product_ids], columns=['transaction_date', 'product_id'])


all_combinations['transaction_date'] = pd.to_datetime(all_combinations['transaction_date'])
final_out['transaction_date'] = pd.to_datetime(final_out['transaction_date'])

merged_data = pd.merge(all_combinations, final_out, on=['transaction_date', 'product_id'], how='left')


merged_data['quantity'].fillna(0, inplace=True)
merged_data

merged_data.to_csv('Top3TeaCoffee.csv', index=False)